### ISSUE TITLE
Don't generate a new Random every Block-Break

### ISSUE THREAD

**Issue by CreepSore** [Fr3shlama/RandomDrops#1]
Do not generate a new "Random"-Object every Block break. Make one on Plugin initialize, and keep that one, so it is more performant.

https://github.com/Fr3shlama/RandomDrops/blob/90ed2e29ec60edee212ee15abec3e1f832ce4a43/src/at/fr3shlama/randomdrops/BlockBreakListener.java#L35

**Comment by Fr3shlama** [comment]
Done!
